'''from frmBase import *
from frmTagManager import *
from frmListEditor import *
from frmCompany import *
from frmCompany2 import *
from frmPerson import *
from frmPerson2 import *
#from frmWidgetMap import *
from frmActivity import *
from frmProgramSettings import *
from frmEquipmentTree import *
from frmTreeBuilder import *
from frmEquipment import *
from frmTaskGroup import *
from frmEquipmentSelector import *
from frmDocumentGenerator import *
from frmDocument import *'''